apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
spec:
  type: NodePort
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080
      nodePort: 30005
