---
apiVersion: v1
kind: Service
metadata:
  name: linkding-service
spec:
  type: NodePort
  selector:
    app: linkding
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30002
