---
apiVersion: v1
kind: Service
metadata:
  name: wireshark-service
spec:
  type: NodePort
  selector:
    app: wireshark
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30006
