apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: homelab
  sources:
    - repoURL: https://jameswynn.github.io/helm-charts
      chart: homepage
      targetRevision: "2.0.1"
      helm:
        valueFiles:
          - $values/applications/homepage/values.yaml
    - repoURL: https://github.com/rmjhynes/homelab
      targetRevision: HEAD
      ref: values

  destination:
    # Resources applied to default k3s cluster
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
