apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://jameswynn.github.io/helm-charts
    chart: homepage
    targetRevision: "2.0.1"
    helm:
      valueFiles:
        - https://github.com/rmjhynes/homelab/blob/main/applications/homepage/values.yaml
  destination:
    # Resources applied to default k3s cluster
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
