apiVersion: v1
kind: Service
metadata:
  name: excalidraw-service
spec:
  type: NodePort
  selector:
    app: excalidraw
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001

