apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
        }
        rewrite name home.homelab traefik.kube-system.svc.cluster.local
        rewrite name freshrss.homelab traefik.kube-system.svc.cluster.local
        rewrite name excalidraw.homelab traefik.kube-system.svc.cluster.local
        rewrite name linkding.homelab traefik.kube-system.svc.cluster.local
        rewrite name scratch-map.homelab traefik.kube-system.svc.cluster.local
        forward . 8.8.8.8 1.1.1.1
        cache 30
        loop
        reload
        loadbalance
    }

