---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
spec:
  project: homelab
  sources:
    - repoURL: https://coredns.github.io/helm
      chart: coredns
      targetRevision: 1.40.0
      helm:
        valueFiles: [$values/applications/coredns/values.yaml]
    - repoURL: https://github.com/rmjhynes/homelab
      targetRevision: HEAD
      ref: values
  destination:
    # Resources applied to default k3s cluster
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      # Specifies if resources should be pruned during auto-syncing ( false by
      # default ).
      prune: true
      # Specifies if partial app sync should be executed when resources are
      # changed only in target Kubernetes cluster and no git change detected
      # ( false by default ).
      selfHeal: true
      # Allows deleting all application resources during automatic syncing
      # ( false by default ).
      allowEmpty: false
      syncOptions: [CreateNamespace=true]
