---
isClusterService: true
servers:
  - zones:
      - zone: .
    port: 53
    plugins:
      - name: errors
      - name: health
      - name: ready
      - name: kubernetes
        parameters: cluster.local in-addr.arpa ip6.arpa
        configBlock: |-
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
      - name: rewrite
        configBlock: |-
          name freshrss.homelab traefik.kube-system.svc.cluster.local
          name excalidraw.homelab traefik.kube-system.svc.cluster.local
          name linkding.homelab traefik.kube-system.svc.cluster.local
          name scratch-map.homelab traefik.kube-system.svc.cluster.local
      - name: forward
        parameters: . 8.8.8.8 1.1.1.1
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
