---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rclone-config
  namespace: default
spec:
  encryptedData:
    rclone.conf: AgCPxatOiWIFFtWHKMivHW96a+mtlcboZh9vgsktOE50K/2Hm50zcA/yh65NRVcgxIR8kIg85cpNyRRDgIMKdTa6n1Q2S7+17L3URbV9qDupff+m/Nj3rk7Ej9Vs6f/eQ1Ty8Vaz7UgVFkCMjDrf/iaQQQ8dgcDdvvClKhAtSVDcbUu/HkvG1saUjuPn3y6qbdhS2j459BOvckrkByFyh1JRfOB8jVFaKFCxw86bXnSnbTijIJJyMCXpAA1mF3BrwPKMjUCxO8yWjc8iDm7YwXaYkSe3bLMPQaMtpaSqcnM0RkYxJcRFhpslIolj195zuxhsJ8CwoXfVGcIFwhEPO1kDtnluDFli+AYb+ehMX1fBGU27HO+AUMeAjBHk4WxfQ9u/2ugDJuufZIZNEX8F0W8zw+9AhGYO0FWmHiRkZZdiFHpzu7D+34rnmX2kE+75hfWGG39K1bvAdOVneWHOvI297kybA93GnDSFV2+QsU2RtQ3TK8cLMrgcEoXYiIOP4W1R12UYv7cSXzpvmMrNPqI6YnmB+xiftc/7TKOBQBE0+UNMNhRxofcGLYE2zsq476icChbjUxLqx80tN/yyBunSvGTahx6vZAnaoSJPI5z7ERSRofigklvXPPrmTAlm9RraSEQON4mmszrj6dKKTRw+4nZ21sXtA5b2WnaXhq9rgeHqJ4FBShSETqYgmiO5ky09vKg3AJ/FhCnDZuwM68I95wrb74tOs9QYNczsEiFBt3Sea6tUtXTVBfDsbpVLItVcDYGFiF4ja7qgbZSeTHoAV+c1PgMn4F15aasiLqcHXaLwlNGVotCKIytrGA88HbZIZ6YQsMFxjGZuU38hut4tOodZ7hV7YxBKJi4Mqwd7uEkgelUujYeLtk8R8DdRCvZsqgH0pakgtJP6Z27lp43OlW4O1RIP4H1sBBWLD5t6n+hb7Fp5IRwR+ZYZd5kkcviEZ6U+Xd8EriD6v10Y8hry9wdE2nwAY5GDdoorGm5JNyIWlnIEjyRNl+JaSWFZpqwyRfa+vV+uCouQOjbXSqIPU5jbruKawgWLo0SiwOPzInYftZf1w2/IPztjmLNwTbsE4ufNmmFsWOn4oMcXbpDj+K3CmP+1KwliujLcm11YGV2NE+QgBdhSiiM/L3WhEXExiB8gkHaQKUNgzM92vgXo8T1XM081c0pFLHYz/XUvNVx/RYgSfRUkQTg8VOiu+eHNrwHJfrTmHXVK8EhlyrD9NJmqOIsXk835x4EeQFPoOV+P8ea+8JGZTmnA8yld182z5+42CH5a2XDiEYX5+cyjSw7BLYucf4tmhhkcQNYpo0aI/3074l8mMpR97Poqp3yC3zbEL/GD0c+0reJgxz/DKtkC7cQ6bgI3MWSimafbTVbWpR8Uh9Zd0DB4n/vPsHpufoEe4I67SGhlcLUiQttT6ngYH/CUBaabpz6wbYosYt6OFBhl9+bRCduGbB4GNLK5XUm/vhleXVH5ku5Cs4T8ftwI1xKpGJSpO00wav3WIa7NVnlM8AaNz+x7COE5z9IHFUQd2KcYXfOwRTJELiah8LUV2wvh0ECFlRH54xE7X7mayhI6KRALKCPOHjN5mlronSJx2J+Ux8T+myxB8HKrh8nM/9da3DKplgcQjep2sUFuUu3RZPR6+tKeRnhpYJqP8RZsKlZq3gv9jisBwTeb9LxCPdSsEsk=
  template:
    metadata:
      creationTimestamp: null
      name: rclone-config
      namespace: default
    type: Opaque
