---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-backup-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeName: freshrss-backup-pv
