apiVersion: v1
kind: Service
metadata:
  name: freshrss-service
spec:
  type: NodePort
  selector:
    app: freshrss
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
