apiVersion: v1
kind: Pod
metadata:
  name: freshrss
  labels:
    app: freshrss
spec:
  containers:
  - name: freshrss
    image: freshrss/freshrss:latest
    env:
    - name: FRESHRSS_USER
      valueFrom:
        configMapKeyRef:
          name: freshrss-config
          key: freshrss-user
