---
apiVersion: v1
kind: Service
metadata:
  name: scratch-map-service
spec:
  type: NodePort
  selector:
    app: scratch-map
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003
