---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-service
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
      nodePort: 30007
